# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SupabaseCli < Formula
  desc "Supabase CLI"
  homepage "https://github.com/Colt-Builders-Corp/supabase-cli"
  version "0.26.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Colt-Builders-Corp/supabase-cli/releases/download/v0.26.4/supabase-cli_0.26.4_darwin_arm64.tar.gz"
      sha256 "49e73f66534b574a95d5b994cfe03186c23d4114a1299084245035234fe6c813"

      def install
        bin.install "supabase"
        (bash_completion/"supabase").write `#{bin}/supabase completion bash`
        (fish_completion/"supabase.fish").write `#{bin}/supabase completion fish`
        (zsh_completion/"_supabase").write `#{bin}/supabase completion zsh`
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Colt-Builders-Corp/supabase-cli/releases/download/v0.26.4/supabase-cli_0.26.4_darwin_amd64.tar.gz"
      sha256 "cab56fa8230217e9bc16bf36f3ee6f2dcd41c5fbe3f11fd708293aaad3ecd312"

      def install
        bin.install "supabase"
        (bash_completion/"supabase").write `#{bin}/supabase completion bash`
        (fish_completion/"supabase.fish").write `#{bin}/supabase completion fish`
        (zsh_completion/"_supabase").write `#{bin}/supabase completion zsh`
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Colt-Builders-Corp/supabase-cli/releases/download/v0.26.4/supabase-cli_0.26.4_linux_amd64.tar.gz"
      sha256 "b61fcc7da3fda62fc267fdc8ea61e342c1950e373765a8fe0e86ce8a39f4ecb6"

      def install
        bin.install "supabase"
        (bash_completion/"supabase").write `#{bin}/supabase completion bash`
        (fish_completion/"supabase.fish").write `#{bin}/supabase completion fish`
        (zsh_completion/"_supabase").write `#{bin}/supabase completion zsh`
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Colt-Builders-Corp/supabase-cli/releases/download/v0.26.4/supabase-cli_0.26.4_linux_arm64.tar.gz"
      sha256 "8aa983f76749ac0f7dd3aa65abb7c8adebcc6bd7acc944b45c0f74d4984b86b5"

      def install
        bin.install "supabase"
        (bash_completion/"supabase").write `#{bin}/supabase completion bash`
        (fish_completion/"supabase.fish").write `#{bin}/supabase completion fish`
        (zsh_completion/"_supabase").write `#{bin}/supabase completion zsh`
      end
    end
  end
end
