# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SupabaseCli < Formula
  desc "Supabase CLI"
  homepage "https://github.com/Colt-Builders-Corp/supabase-cli"
  version "0.26.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Colt-Builders-Corp/supabase-cli/releases/download/v0.26.6/supabase-cli_0.26.6_darwin_arm64.tar.gz"
      sha256 "d3941566bd1b98eebe1aca6ed6823e9055c31aa76f49c670074cc73c7cd589cc"

      def install
        bin.install "supabase"
        (bash_completion/"supabase").write `#{bin}/supabase completion bash`
        (fish_completion/"supabase.fish").write `#{bin}/supabase completion fish`
        (zsh_completion/"_supabase").write `#{bin}/supabase completion zsh`
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Colt-Builders-Corp/supabase-cli/releases/download/v0.26.6/supabase-cli_0.26.6_darwin_amd64.tar.gz"
      sha256 "5231cde5a45f92baceb202db21fb91b20e777db7f4e95483c3b9220043871590"

      def install
        bin.install "supabase"
        (bash_completion/"supabase").write `#{bin}/supabase completion bash`
        (fish_completion/"supabase.fish").write `#{bin}/supabase completion fish`
        (zsh_completion/"_supabase").write `#{bin}/supabase completion zsh`
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Colt-Builders-Corp/supabase-cli/releases/download/v0.26.6/supabase-cli_0.26.6_linux_arm64.tar.gz"
      sha256 "4bd80234a79c93d77aff12fdda097cc56ee1ea0eaa129bee632c75fd53d24d8d"

      def install
        bin.install "supabase"
        (bash_completion/"supabase").write `#{bin}/supabase completion bash`
        (fish_completion/"supabase.fish").write `#{bin}/supabase completion fish`
        (zsh_completion/"_supabase").write `#{bin}/supabase completion zsh`
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Colt-Builders-Corp/supabase-cli/releases/download/v0.26.6/supabase-cli_0.26.6_linux_amd64.tar.gz"
      sha256 "672adc14bd0cf78cae7adfda8490b09e89674a5509f12229cfa1d7d73dd29f42"

      def install
        bin.install "supabase"
        (bash_completion/"supabase").write `#{bin}/supabase completion bash`
        (fish_completion/"supabase.fish").write `#{bin}/supabase completion fish`
        (zsh_completion/"_supabase").write `#{bin}/supabase completion zsh`
      end
    end
  end
end
