# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SupabaseCli < Formula
  desc "Supabase CLI"
  homepage "https://github.com/Colt-Builders-Corp/supabase-cli"
  version "0.26.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Colt-Builders-Corp/supabase-cli/releases/download/v0.26.5/supabase-cli_0.26.5_darwin_amd64.tar.gz"
      sha256 "bef69ed1b6f7b414240db1883327fd4e3ab0f2d4ad163974d5cb333c919ef219"

      def install
        bin.install "supabase"
        (bash_completion/"supabase").write `#{bin}/supabase completion bash`
        (fish_completion/"supabase.fish").write `#{bin}/supabase completion fish`
        (zsh_completion/"_supabase").write `#{bin}/supabase completion zsh`
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Colt-Builders-Corp/supabase-cli/releases/download/v0.26.5/supabase-cli_0.26.5_darwin_arm64.tar.gz"
      sha256 "6df5f2f76d1367acb996d3ef4031290005fae2e6923e72663f6434183287985b"

      def install
        bin.install "supabase"
        (bash_completion/"supabase").write `#{bin}/supabase completion bash`
        (fish_completion/"supabase.fish").write `#{bin}/supabase completion fish`
        (zsh_completion/"_supabase").write `#{bin}/supabase completion zsh`
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Colt-Builders-Corp/supabase-cli/releases/download/v0.26.5/supabase-cli_0.26.5_linux_amd64.tar.gz"
      sha256 "650f6d3e7c45c698fb49b795cbe130ff1648f5bfeb74f55a87fcf63033cf5ca7"

      def install
        bin.install "supabase"
        (bash_completion/"supabase").write `#{bin}/supabase completion bash`
        (fish_completion/"supabase.fish").write `#{bin}/supabase completion fish`
        (zsh_completion/"_supabase").write `#{bin}/supabase completion zsh`
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Colt-Builders-Corp/supabase-cli/releases/download/v0.26.5/supabase-cli_0.26.5_linux_arm64.tar.gz"
      sha256 "0c5ad216f36d760a75fede569e0e0f8393b0629b22921b1fbddc2c07a6f9ffd1"

      def install
        bin.install "supabase"
        (bash_completion/"supabase").write `#{bin}/supabase completion bash`
        (fish_completion/"supabase.fish").write `#{bin}/supabase completion fish`
        (zsh_completion/"_supabase").write `#{bin}/supabase completion zsh`
      end
    end
  end
end
